### ISSUE TITLE
complete documentation steps

### ISSUE THREAD

**Issue by sugizo** [miskibin/py-draughts#10]
**environment** 
google colab

following steps in pypi and your github
when execute
`board = get_board('standard', "W:W4,11,28,31,K33,K34,38,40,K41,43,K44,45,K46,47:BK3,21,27,32")`

**result**
```
NameError                                 Traceback (most recent call last)
[<ipython-input-2-9f0da245e050>](https://localhost:8080/#) in <cell line: 1>()
----> 1 board = get_board('standard', "W:W4,11,28,31,K33,K34,38,40,K41,43,K44,45,K46,47:BK3,21,27,32")

NameError: name 'get_board' is not defined
```

when execute
`board.turn`

**result**
```
NameError                                 Traceback (most recent call last)
[<ipython-input-3-559e7bbe27d3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 board.turn

NameError: name 'board' is not defined
```

**quick analysis**
perhaps the problem is about the function is not import first, for board and get_board()

**suggestion**
nice to have complete documentation steps

best regards

**Comment by miskibin** [comment]
Looks good now.
![image](https://github.com/michalskibinski109/py-draughts/assets/77834536/4988cd23-da98-4a11-acef-4966a6a1f101)
